### ISSUE TITLE
Firefox web extension file is corrupt

### ISSUE THREAD

**Issue by therealjeffg** [jazz-soft/web-midi#3]
When trying to install the web extension from addons.mozilla.org, Firefox Dev Edition ( 87 ) claims the file is corrupt - perhaps the signing key?

This is the file it give me: [file](https://addons.mozilla.org/firefox/downloads/file/3746110/web_midi_api-1.0.2.3-fx.xpi)

After downloading and unzipping the file, I am able to successfully use it in a demo by loading it in dev mode.

Screenshot from this morning:

![image](https://user-images.githubusercontent.com/104315/111818976-07fa0180-889d-11eb-9273-3f4a60fe0874.png)

**Comment by jazz-soft** [comment]
Thanks a lot for fast notice!
Fixed version is online.

**Comment by therealjeffg** [comment]
Thanks - just happened to want to test that today.

**Comment by jazz-soft** [comment]
Lucky to me! It was just broken a few hours before you noticed it!
:)
